# Generated by Django 4.2.2 on 2023-06-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('short_name', models.CharField(max_length=20, verbose_name='nombre_corto')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
            ],
        ),
    ]
