# Generated by Django 4.2.2 on 2023-06-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='nombre_corto'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
